/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "error-container": "#93000a",
        "primary-container": "#22c55e",
        "primary-fixed-dim": "#4ae176",
        "on-background": "#dce5d9",
        "surface-container-low": "#161d16",
        "secondary": "#ffb690",
        "on-tertiary-fixed": "#181b24",
        "on-surface": "#dce5d9",
        "surface-container-highest": "#2f372e",
        "surface-container-high": "#242c24",
        "tertiary": "#c5c6d1",
        "outline": "#869585",
        "on-secondary": "#552100",
        "on-primary-fixed-variant": "#005321",
        "tertiary-fixed": "#e0e2ed",
        "surface-container": "#1a221a",
        "on-error": "#690005",
        "inverse-primary": "#006e2f",
        "outline-variant": "#3d4a3d",
        "primary": "#4be277",
        "error": "#ffb4ab",
        "surface-bright": "#333b33",
        "tertiary-fixed-dim": "#c4c6d1",
        "surface-variant": "#2f372e",
        "surface-tint": "#4ae176",
        "tertiary-container": "#a9abb6",
        "on-tertiary-fixed-variant": "#444650",
        "on-secondary-fixed-variant": "#783200",
        "on-secondary-fixed": "#341100",
        "inverse-surface": "#dce5d9",
        "on-error-container": "#ffdad6",
        "secondary-container": "#ec6a06",
        "on-secondary-container": "#4a1c00",
        "inverse-on-surface": "#2a322a",
        "on-tertiary": "#2d3039",
        "on-primary-fixed": "#002109",
        "surface": "#0e150e",
        "on-primary-container": "#004b1e",
        "on-primary": "#003915",
        "primary-fixed": "#6bff8f",
        "on-surface-variant": "#bccbb9",
        "background": "#0b0d10",
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "margin-desktop": "40px",
        "md": "16px",
        "margin-mobile": "16px",
        "xs": "4px",
        "xl": "32px",
        "sm": "8px",
        "unit": "4px",
        "2xl": "48px",
        "lg": "24px",
        "gutter": "20px",
        "3xl": "64px"
      },
      fontFamily: {
        "display-lg": ["Outfit", "sans-serif"],
        "headline-sm": ["Outfit", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "headline-lg": ["Outfit", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "headline-md": ["Outfit", "sans-serif"],
        "headline-lg-mobile": ["Outfit", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"]
      },
      fontSize: {
        "display-lg": ["48px", {"lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700"}],
        "headline-sm": ["20px", {"lineHeight": "28px", "fontWeight": "600"}],
        "body-md": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
        "headline-lg": ["32px", {"lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "700"}],
        "label-md": ["12px", {"lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "600"}],
        "headline-md": ["24px", {"lineHeight": "32px", "fontWeight": "600"}],
        "headline-lg-mobile": ["28px", {"lineHeight": "36px", "fontWeight": "700"}],
        "body-lg": ["18px", {"lineHeight": "28px", "fontWeight": "400"}],
        "body-sm": ["14px", {"lineHeight": "20px", "fontWeight": "400"}]
      }
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
  ],
}
